name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1

      # Runs a single command using the runners shell
      - name: Build Web Release
        run: flutter build web --web-renderer auto --base-href /sharif_health_app/

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ezcar.ir
          username: salamat
          port: 22
          overwrite: true
          password: "&hW3YdTwnFUDNHa3"
          source: "build/web/*"
          target: "/home/salamat/app_backups"

      - name: Move File to Web App directory
        uses: appleboy/ssh-action@master
        with:
          script: "sh /home/salamat/app_backups/deploy.sh"
          host: ezcar.ir
          username: salamat
          password: "&hW3YdTwnFUDNHa3"
          port: 22


      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2

      - name: Build android Release
        run: flutter build apk

      - name: rename apk file
        run: mv build/app/outputs/apk/release/app-release.apk ./salamat.apk

      - name: copy apk file via ssh pass
        uses: appleboy/scp-action@master
        with:
          host: ezcar.ir
          username: salamat
          password: "&hW3YdTwnFUDNHa3"
          port: 22
          overwrite: true
          source: "salamat.apk"
          target: "/var/www/html/download"